#define DRONE_FCB_RESTARTED "d_f_r"
#define DRONE_ARMED "d_f_a"
#define DRONE_DISARMED "d_f_d"
#define DRONE_FLYING "d_f_f"
#define DRONE_LANDED "d_f_l"
#define DRONE_MODE_ALT_HOLD "d_f_ah"
#define DRONE_MODE_GUIDED "d_f_gdd"
#define DRONE_MODE_AUTO "d_f_auto"
#define DRONE_MODE_RTL "d_f_rtl"
#define DRONE_MODE_STABILIZE "d_f_stb"
#define DRONE_MODE_LOITER "d_f_loiter"
#define DRONE_MODE_POSHOLD "d_f_ph"
#define DRONE_CONNECTED "d_f_c"
#define DRONE_DISCONNECTED "d_f_dc"
#define DRONE_HOME_SET "d_f_hs"
#define DRONE_MISSION_STARTED "d_f_ms"
#define DRONE_MISSION_COMPLETED "d_f_mc"

